version: "3.9"

services:
  db:
    image: postgres:15
    container_name: subs-db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    restart: unless-stopped

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: subs-collector
    env_file:
      - .env
    environment:
      POSTGRES_HOST: "db"
    ports:
      - "${APP_PORT}:8080"
    depends_on:
      - db
    restart: unless-stopped

volumes:
  db_data: